filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

#============================= Filebeat modules ===============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1

#============================== Kibana =====================================

setup.kibana:
  host: "10.0.1.24:5601"

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["http://10.0.1.19:9200"]

#================================ Processors =====================================

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

