---

- name: Download grafana
  hosts: grafana_server
  become: yes

  tasks:
  - name: Download grafana
    get_url:
      url: https://dl.grafana.com/oss/release/grafana_10.1.0_amd64.deb
      dest: /home/user/

  tasks:
  - name: install grafana
    ansible.builtin.apt:
      deb: /home/user/grafana_10.1.0_amd64.deb